#ifndef _CHIPTUNE_CONFIG_INTERNAL_H_
#define _CHIPTUNE_CONFIG_INTERNAL_H_

//#define _USE_ACCUMULATED_DELTA_TICK_AS_TIMEBASE
//#define _USE_SCALED_RECIPROCAL_MULTIPLIER_FOR_WAVE_AMPLITUDE_NORMALIZATION
//#define _USE_STATIC_RESOURCE_ALLOCATION

#define _PRINT_DEVELOPING
//#define _PRINT_MIDI_NOTE
//#define _PRINT_MIDI_CONTROLCHANGE
//#define _PRINT_MIDI_PROGRAMCHANGE
//#define _PRINT_MIDI_CHANNELPRESSURE
//#define _PRINT_MIDI_PITCH_WHEEL
//#define _PRINT_EVENT_TRIGGERING


#ifdef _USE_STATIC_RESOURCE_ALLOCATION
	#define OSCILLATOR_POOL_CAPACITY			(512)
	#define MIDI_EFFECT_ASSOCIATION_LINK_NODE_POOL_CAPACITY	(256)
	#define PHASER_FILTER_STATE_POOL_CAPACITY	(256)

	#define EVENT_POOL_CAPACITY					(1024)
#else
	#define OSCILLATOR_POOL_CAPACITY			(64)
	#define MAX_OSCILLATOR_NODE_CAPACITY		(8192)
	#define MIDI_EFFECT_ASSOCIATION_LINK_NODE_POOL_CAPACITY	(64)
	#define MAX_MIDI_EFFECT_ASSOCIATION_LINK_NODE_CAPACITY	(MAX_OSCILLATOR_NODE_CAPACITY/2)
	#define PHASER_FILTER_STATE_POOL_CAPACITY	(32)
	#define MAX_PHASER_FILTER_STATE_CAPACITY	(INT16_MAX)

	#define EVENT_POOL_CAPACITY					(64)
	#define MAX_EVENT_CAPACITY					(8192)
#endif


#endif // _CHIPTUNE_CONFIG_INTERNAL_H_
