#ifndef _CHIPTUNE_VERSION_INTERNAL_H_
#define _CHIPTUNE_VERSION_INTERNAL_H_

#define CHIPTUNE_VERSION_MAJOR					(0)
#define CHIPTUNE_VERSION_MINOR					(1)
#define CHIPTUNE_VERSION_MICRO					(0)

#endif // _CHIPTUNE_VERSION_INTERNAL_H_
