#ifndef _CHIPTUNE_VERSION_INTERNAL_H_
#define _CHIPTUNE_VERSION_INTERNAL_H_

#define CHIPTUNE_VERSION_MAJOR					(0)
#define CHIPTUNE_VERSION_MINOR					(1)
#define CHIPTUNE_VERSION_MICRO					(1)

#define CHIPTUNE_VERSION_STRINGIFY_(VALUE)		#VALUE
#define CHIPTUNE_VERSION_STRINGIFY(VALUE)		CHIPTUNE_VERSION_STRINGIFY_(VALUE)

#define CHIPTUNE_VERSION_STRING					\
	CHIPTUNE_VERSION_STRINGIFY(CHIPTUNE_VERSION_MAJOR) "." \
	CHIPTUNE_VERSION_STRINGIFY(CHIPTUNE_VERSION_MINOR) "." \
	CHIPTUNE_VERSION_STRINGIFY(CHIPTUNE_VERSION_MICRO)

#endif // _CHIPTUNE_VERSION_INTERNAL_H_
