#ifndef _CHIPTUNE_COMMON_INTERNAL_H_
#define _CHIPTUNE_COMMON_INTERNAL_H_

#include <stdbool.h>
#include <stdint.h>
//#define _DEBUG_ANKOKU_BUTOUKAI_FAST_TO_ENDING

//#define _INCREMENTAL_SAMPLE_INDEX
//#define _RIGHT_SHIFT_FOR_NORMALIZING_AMPLITUDE

#define _PRINT_DEVELOPING
#define _PRINT_MIDI_SETUP
#define _PRINT_NOTE_OPERATION
//#define _PRINT_OSCILLATOR_TRANSITION

//#define _CHECK_OCCUPIED_OSCILLATOR_LIST
//#define _CHECK_EVENT_LIST

#define MIDI_MAX_CHANNEL_NUMBER						(16)
#define MIDI_CC_CENTER_VALUE						(64)
#define MIDI_PITCH_WHEEL_CENTER						(0x2000)
#define MIDI_DEFAULT_PITCH_WHEEL_BEND_RANGE_IN_SEMITONES	\
															(2 * 2)

#define MIDI_CC_RPN_NULL							((127 << 8) + 127)


#endif // _CHIPTUNE_COMMON_INTERNAL_H_
