#ifndef _CHIPTUNE_CONFIG_INTERNAL_H_
#define _CHIPTUNE_CONFIG_INTERNAL_H_

//#define _USE_ACCUMULATED_DELTA_TICK_AS_TIMEBASE
//#define _USE_SCALED_RECIPROCAL_MULTIPLIER_FOR_WAVE_AMPLITUDE_NORMALIZATION
//#define _USE_STATIC_RESOURCE_ALLOCATION

#define _PRINT_DEVELOPING
//#define _PRINT_MIDI_NOTE
//#define _PRINT_MIDI_CONTROLCHANGE
//#define _PRINT_MIDI_PROGRAMCHANGE
//#define _PRINT_MIDI_CHANNELPRESSURE
//#define _PRINT_MIDI_PITCH_WHEEL
//#define _PRINT_EVENT_TRIGGERING

#endif // _CHIPTUNE_CONFIG_INTERNAL_H_
